name: C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: look for curl
      run: find / -type f -name "curl.h"
    - name: cmake
      run: cmake .
    - name: make
      run: make

